FROM php:7.2-apache
MAINTAINER jose nazario <jose@monkey.org>
LABEL version="1.0" description="nosqli-labs Docker image"

# modifying from https://hub.docker.com/r/spittet/php-mongodb/
RUN apt update 
RUN apt install -y gpg wget
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - 
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get -qq update && \
    apt-get install -y mongodb-org && \
	apt-get install -y libssl-dev unzip && \
    pecl install mongodb && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \	
    docker-php-ext-enable mongodb && \
	apt-get -qy autoremove && \
	apt-get clean && \
	mkdir -p /data/db && \
	/usr/bin/mongod --fork --syslog

COPY . /var/www/html
RUN sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/user_lookup.php && \
	sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/populate_db.php && \
	sed -i s/"localhost:27017"/"mongo:27017"/g /var/www/html/guess_the_key.php
